[package]
name = "openrpsee"
version = "0.1.0"
edition = "2024"

[dependencies]

documented = "0.9"
jsonrpsee = { version = "0.24", features = ["server"] }
quote = "1"
schemars = "1"
serde = "1"
serde_json = "1"
syn = { version = "2", features = ["full"] }
